/**
 * Created by herisetiawan on 2/16/17.
 */
export const LOAD_POKEMONS_SUCCESS = 'LOAD_POKEMONS_SUCCESS';
export const LOAD_POKEMON_DETAILS_SUCCESS = 'LOAD_POKEMON_DETAILS_SUCCESS';
export const SET_POKEMON_DETAIL = 'SET_POKEMON_DETAIL';
export const GET_POKEMON_SPEC = 'GET_POKEMON_SPEC';
export const GET_POKEMON_SPEC_SUCCESS = 'GET_POKEMON_SPEC_SUCCESS';
export const LOAD_PARAMS = 'LOAD_PARAMS';
