/**
 * Created by herisetiawan on 2/16/17.
 */
export const LOAD_POKEMONS_SUCCESS = 'LOAD_POKEMONS_SUCCESS';
export const LOAD_POKEMON_DETAILS_SUCCESS = 'LOAD_POKEMON_DETAILS_SUCCESS';
export const SET_POKEMON_DETAIL = 'SET_POKEMON_DETAIL';
